module Softlayer
  module Container
    autoload :Exception, 'softlayer/container/exception'
    autoload :Graph, 'softlayer/container/graph'
    autoload :Message, 'softlayer/container/message'
    autoload :Account, 'softlayer/container/account'
    autoload :Auxiliary, 'softlayer/container/auxiliary'
    autoload :Bandwidth, 'softlayer/container/bandwidth'
    autoload :Billing, 'softlayer/container/billing'
    autoload :Catalyst, 'softlayer/container/catalyst'
    autoload :Collection, 'softlayer/container/collection'
    autoload :Disk, 'softlayer/container/disk'
    autoload :Dns, 'softlayer/container/dns'
    autoload :Hardware, 'softlayer/container/hardware'
    autoload :KnowledgeLayer, 'softlayer/container/knowledge_layer'
    autoload :Metric, 'softlayer/container/metric'
    autoload :Monitoring, 'softlayer/container/monitoring'
    autoload :Network, 'softlayer/container/network'
    autoload :Notification, 'softlayer/container/notification'
    autoload :Product, 'softlayer/container/product'
    autoload :Provisioning, 'softlayer/container/provisioning'
    autoload :Referral, 'softlayer/container/referral'
    autoload :RemoteManagement, 'softlayer/container/remote_management'
    autoload :Search, 'softlayer/container/search'
    autoload :Software, 'softlayer/container/software'
    autoload :Tax, 'softlayer/container/tax'
    autoload :Ticket, 'softlayer/container/ticket'
    autoload :User, 'softlayer/container/user'
    autoload :Utility, 'softlayer/container/utility'
    autoload :Virtual, 'softlayer/container/virtual'
  end
end
